substitutions:
  name: huawei-r4850-controller
  device_description: "Control the power output of a Huawei R4850 via CAN-Bus"

esphome:
  name: ${name}
  comment: ${device_description}
  friendly_name: HuaweiR4850

external_components:
  - source: components

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG
  logs:
    canbus: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret r4850_encryptionkey

ota:
  password: !secret r4850_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  ap:
    ssid: "Huawei Fallback Hotspot"
    password: "F47oQ9E8K5iD"

web_server:

captive_portal:

canbus:
  - platform: esp32_can
    id: can
    tx_pin: GPIO14
    rx_pin: GPIO27
    use_extended_id: true
    can_id: 0
    bit_rate: 125kbps


huawei_r4850:
# The state of this sensor (instantaneous power in watt) is used as source                                                         
  power_id: powermeter0   
  canbus_id: can
  update_interval: 5s
  

sensor:
  - platform: huawei_r4850
    output_voltage:
      name: Output voltage
    output_current:
      name: Output current
    output_power:
      name: Output power
    input_voltage:
      name: Input voltage
    input_current:
      name: Input current
    input_power:
      name: Input power
    input_frequency:
      name: Input frequency
    efficiency:
      name: Efficiency
    input_temp:
      name: Input temperature
    output_temp:
      name: Output temperature
      
  # import smartmeter reading from homeassistant
  # requires the "api" component see above
  - platform: homeassistant
    id: powermeter0
    name: "${name} smartmeter instantaneous power"
    entity_id: sensor.wohnungszahler_akt_vebrauch
    filters:
      - throttle_average: 15s   

number:
  - platform: huawei_r4850
    output_voltage:
      name: Set output voltage
    max_output_current:
      name: Max output current

button:
  - platform: huawei_r4850
    set_offline_values:
      name: Set offline values
      